common:
  macros:
  - USE_HAL_DRIVER
  - STM32F407xx
  includes:
  - Drivers
  - Drivers/CMSIS
  - Drivers/CMSIS/Device
  - Drivers/CMSIS/Device/ST
  - Drivers/CMSIS/Device/ST/STM32F4xx
  - Drivers/CMSIS/Device/ST/STM32F4xx/Include
  - Drivers/CMSIS/Include
  - Drivers/STM32F4xx_HAL_Driver
  - Drivers/STM32F4xx_HAL_Driver/Inc
  - Drivers/STM32F4xx_HAL_Driver/Inc/Legacy
  - Drivers/nRF24L01_Driver
  - Drivers/nRF24L01_Driver/Inc
  - Middlewares
  - Middlewares/ST
  - Middlewares/ST/STM32_USB_Device_Library
  - Middlewares/ST/STM32_USB_Device_Library/Class
  - Middlewares/ST/STM32_USB_Device_Library/Class/CDC
  - Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc
  - Middlewares/ST/STM32_USB_Device_Library/Core
  - Middlewares/ST/STM32_USB_Device_Library/Core/Inc
  - Libraries
  - Libraries/mavlink
  - Libraries/mavlink/car
  - Inc
  sources:
    Drivers:
    - Drivers/nRF24L01_Driver/Src
    - Drivers/STM32F4xx_HAL_Driver/Src
    Middlewares:
    - Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src/usbd_cdc.c
    - Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_core.c
    - Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.c
    - Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ioreq.c
    Src:
    - Src
  target:
  - stm32f407ve
tool_specific:
  iar_arm:
    sources:
      StartUp:
      - IDE/IAR
    linker_file:
    - IDE/IAR/stm32f407xx_flash.icf
